### ISSUE TITLE
support multiple error codes

### ISSUE THREAD

**Issue by ghost** [geofflane/grails-constraints#10]
When writing a custom grails constraint, the validation might fail for multiple reasons and you can instruct grails to use a different error message code in each case. For example, a ZIP code validator might fail because the ZIP is the wrong length, or the ZIP doesn't exist.

Grails also allows you to specify custom arguments that will be used when those messages are resolved. Here's an example of how to use both these features with a Grails custom validator: 

```
    zipCode(validator: {zipCode, target ->

        def zipCodeLength = 5

        if (zipCode?.size() != zipCodeLength) {

            // In this case the message code "className.propertyName.size" will be used and zipCodeLength will be passed 
            // as the message argument with index 3
            return ['size', zipCodeLength]
        }

        if (!target.locationManager.findZipCode(zipCode)) {

            // In this case the message code "className.propertyName.invalid" will be used
            return 'invalid'
        }
    })
```

It seems that the failureCode property allows you to use a different message for each class that uses a constraint. However, for a given class it seems you're limited to one error message and there's no way to pass custom arguments when the message is resolved.

BTW, thanks a lot for the plugin, seems to have been very well thought out.

**Comment by ghost** [comment]
My own opinion is that the ability to specify multiple error codes is a lot more important than the ability to pass custom arguments to the error message

**Comment by geofflane** [comment]
Good idea. Something I'll have to look into.

**Comment by geofflane** [comment]
@domurtag As an aside, I think there's a workaround for your issue. The third (optional) parameter to the validate closure is 'errors' which is an instance of org.springframework.validation.Errors. In that guy you can set any values you want.
e.g.
```def args = [constraintPropertyName, val, params.op, params.field]
errors.rejectValue(constraintPropertyName, 'default.invalid.random.message', args, 'Invalid value')

```
```

**Comment by geofflane** [comment]
A contribution added this support for multiple kinds of return types. So now if you return a string, that will be used as the error message. You can also return an Array or Collection where the first value is a format string and the rest are arguments to the format String. e.g.

```
def validate = { val ->
    return ["error.code", "foo", "bar"]
}
```

Will show up officially in 0.8
