### ISSUE TITLE
Grails 2.0 Unit tests

### ISSUE THREAD

**Issue by jamescookie** [geofflane/grails-constraints#11]
Just trying up upgrade my project to Grails 2.0 and run into a problem with this plugin.

Some of my domain classes share a need for complicated validation, so I use your plugin to extract it to a common constraint. However when running my unit tests in Grails 2.0 I get:

`java.lang.IllegalArgumentException: ServletContext must not be null`

When I attempt to construct a Domain class with this custom constraint. If I comment out the constraint, everything works fine.

**Comment by geofflane** [comment]
Would it be possible to share the constraint that's causing the issue? I just upgraded the plugin to Grails 2.0 and all the tests pass and my little sample app works as well.

Thanks.

**Comment by jamescookie** [comment]
I don't think it's the constraint itself that is causing the problem as I removed all the code from inside it and the tests still fail. I can try to produce a small app that has the issue?

**Comment by geofflane** [comment]
@jamescookie That would be great to get a small app to produce the issue.

**Comment by jamescookie** [comment]
So I tried (a lot) to reproduce this in a small app, but found I couldn't. After recreating most of my original app in the new one, I finally tracked down the problem to some methods in the Domain object's controller that needed to be made private. I have lost the will to live trying to figure out how that could possibly make my unit tests fail. I am happy to close this issue as I'm sure it's something other than this plugin causing the problems.

**Comment by geofflane** [comment]
@jamescookie While I'm glad the plugin didn't cause it, I feel your pain. A lot of modern frameworks seem to make us so much more productive and then we lose all of the time saved tracking down seemingly random problems like the one you mention!
