### ISSUE TITLE
Potential support for @TestFor 

### ISSUE THREAD

**Issue by samcday** [geofflane/grails-constraints#16]
Hi Geoff,

Pull request #15 offers support for @TestMixin annotations in Grails 2 unit tests for Constraints.

There is another feature that can expand this even more, and that's supporting the @TestFor annotation outright. This would mean instead of this:

```
@TestMixin(ConstraintUnitTestMixin)
class MyConstraintTests {
    void testStuff() {
        def constraint = testFor(MyConstraint)

        // Params are automatically mixed in to the test class and exposed
        // to the constraint with the call above.
        params.foo = "bar"

        assert constraint.validate("foo", null, null) == true
    }
}
```

You can do this:

```
@TestFor(MyConstraint)
class MyConstraintTests {
    void testStuff() {
        // No need to setup constraint, it's automatically setup in each test.

        // Params are automatically mixed in to the test class and exposed
        // to the constraint with the call above.
        params.foo = "bar"

        assert constraint.validate("foo", null, null) == true
    }
}
```

@TestFor handles weaving in the relevant mixin class, so in the latter example ConstraintUnitTestMixin would still get mixed into the class at compile time. TestFor has the added avantage of automatically calling testFor<sup>&#x2020;</sup> to setup the class under test in each test method. Sicne this is now the standard in Grails for testing core artefacts like Services/Controllers/Taglibs, it is nice to offer this for custom artefacts like Constraints too.

The caveat is to offer this support a small amount of monkey-patching is required. A hook needs to be added to _Events.groovy to let TestForTransformation know about your custom artefact. Take a look at [how I did it in my of my plugins](https://github.com/samcday/grails-binders/blob/master/scripts/_Events.groovy) and you'll see what I'm talking about.

I [posted](http://grails.1312388.n4.nabble.com/Grails-2-Test-mixins-for-custom-Artefacts-tt4335529.html) about this on the Grails user mailing list and Graeme Rocher responded without any complaints about this approach. He recommended a feature request be raised to have an official API for this in a future version of Grails 2.

So it's up to you really, if you want to add in the small amount of monkey-patching code to _Events.groovy then you can have @TestFor support now, or you can wait until there's an official mechanism to register custom artefacts.

Let me know what you think!

&#x2020; well actually, TestForTransformation automatically calls mock<Artefact Name>, testFor is just a convention and in the ConstraintUnitTestMixin it just calls mockConstraint

**Comment by geofflane** [comment]
The testFor is definitely the 80% solution, so I really appreciate you adding that. Did you ever create an issue for an official API? I'll probably hold off adding this for now...

**Comment by cdeszaq** [comment]
I would advocate for adding @TestFor support sooner than later. Not only does it make this plugin more consistent with testing other core artifacts but it also adds a specific use-case / implementation that an official core testing API request can point to and use for supporting itself. The more an enhancement can show that it would make other things more simple, the more likely it is to get added to the core.

**Comment by samcday** [comment]
@geofflane Have you had a chance to consider merging this in? We've been using it for quite a while now and haven't had a single issue with it on any dev machines/buildservers, so i guess there's safety in simplicity ;)

I logged GRAILS-8691 a while ago as per Graeme's request, but no word from any of the Grails core guys yet. Would definitely be cool to see constraints plugin pick this up along with others to gain some traction in the solution being implemented in `grails-core`.

**Comment by geofflane** [comment]
Ok, thanks for bugging me about it, I just added an _Events and a test and it seems to work. Try it out and let me know.
