### ISSUE TITLE
create-constraint script does not default in package name.

### ISSUE THREAD

**Issue by rrullo** [geofflane/grails-constraints#3]
Steps:
grails create-constraint net.rrullo.tester.FooBar

Creates FooBar in package structure net.rrullo.tester correctly, but does not place a package name in the groovy class.

Fix is simple, update the /src/templates/artifacts/Constraint.groovy from 

class @artifact.name@ {

```
def validate = { propertyValue ->
    // execute validation
}
```

}
- to - 

@artifact.package@class @artifact.name@ {

```
def validate = { propertyValue ->
    // execute validation
}
```

}

**Comment by geofflane** [comment]
Thanks for the fix, this is checked in.
