### ISSUE TITLE
Custom constraints not working within unit tests and mocked domain classes

### ISSUE THREAD

**Issue by rrullo** [geofflane/grails-constraints#4]
I have created a unit test and mocked a domain class and am not seeing my custom constraint being caught.

I'm using mockDomain() to create and work with my domain class.  

I've created a test case that demonstrates the problem within 2 classes http://dl.dropbox.com/u/6783272/constraints-mock.zip.

Just run test-app and the errors demonstrate the problem.

-Bob

**Comment by geofflane** [comment]
Bob,
This might be because it's in the Unit Test phase? Plugins are only loaded in the integration phase. That being said, I haven't done anything with mockDomain, so I'll need to look into that more.

**Comment by javidjamae** [comment]
You may also look into the mockForConstraintsTests function available on GrailsUnitTestCase. This is a common way to test constraints.

**Comment by pmcneil** [comment]
Jeff,

mockForConstraintsTests is used to check constraint validatio. It'd be nice to see custom validations pulled in there instead of relying on integration tests.

**Comment by pmcneil** [comment]
Then again maybe integration tests are better for constraints testing
