### ISSUE TITLE
constraintPropertyName and constraintOwningClass are always null

### ISSUE THREAD

**Issue by mlathe** [geofflane/grails-constraints#6]
I wanted a constraint like the one below. But i always get errors like this:

 Property [null] with value [12/10/10 12:00 AM] is not [>] [releaseDate]

Given this message:

 default.invalid.compare.message=Property [{0}] with value [{1}] is not [{2}] [{3}]

/**
- Use it by doing something like:
-   endDate(compare: [op: '>', field:'startDate'])
-   lowerRange(compare: [op: '<=', field:'upperRange'])
  */
  class CompareConstraint {
  static expectsParams = ['op', 'field']
  
  def validate = { val, target, errors ->
      def compareVal = target."$params.field"
      def result = false
      if (val && compareVal) {
          switch (params.op) {
              case ">":  result = val.compareTo(compareVal) > 0; break
              case ">=": result = val.compareTo(compareVal) >= 0; break
              case "==": result = val.compareTo(compareVal) == 0; break
              case "<=": result = val.compareTo(compareVal) <= 0; break
              case "<":  result = val.compareTo(compareVal) < 0; break
              default: throw new IllegalArgumentException("Invalid operation: " + params.op)
          }
      }
  
  ```
  if (!result) {
      //TODO: constraintPropertyName doesn't seem to get set? not sure why not.
      def args = ArrayUtil.createArray(constraintPropertyName, val, params.op, params.field)
      errors.rejectValue(constraintPropertyName, 'default.invalid.compare.message', args, 'Invalid value')
  }
  
  return true //always return true, since we are manually inserting the error into the errors obj
  ```
  
  }
  }

**Comment by geofflane** [comment]
Sorry for taking so long to get to this! Thanks for the bug report. Those values were only being set in persistent classes. Just checked in a fix for that.
